; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:giga_r1_m7]
platform = ststm32
board = giga_r1_m7
framework = arduino
board_build.arduino.flash_layout = 100_0
board_upload.maximum_size = 2097152
lib_extra_dirs = ../RumpusArduinoLibrary/libraries
lib_deps = 
	lvgl/lvgl
	arduino-libraries/Arduino_GigaDisplay@^1.0.2
	arduino-libraries/Arduino_GigaDisplay_GFX@^1.1.0
	arduino-libraries/Arduino_GigaDisplayTouch@^1.0.1
	arduino-libraries/NTPClient@^3.2.1
	QueueArray
	bblanchon/ArduinoJson@6.21.0
	git@github.com:projectsinflight/RampSoakPID.git
	ojx/GigaAudio @ ^0.1.1
	milesburton/DallasTemperature@^4.0.6
build_flags = 
	-Iinclude
	
	-DLV_CONF_INCLUDE_SIMPLE

[platformio]
extra_configs = ../common.ini
