// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: Public Address

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void dropdownUserChanged(lv_event_t * e);
void PlayButtonPressed(lv_event_t * e);
void BlinkEnabled(lv_event_t * e);
void BlinkDisabled(lv_event_t * e);
void StopButtonPressed(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
