// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "events/events.h"

void UserDropdownEvent(lv_event_t *e)
{
    handleUserDropdownEvent(e);
}