// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: Public Address

#include "ui.h"

void playButtonPressed(lv_event_t *e)
{
	// Your code here
}
