// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: bs_kettle_fill

#include "ui.h"
#include "Globals.h"

lv_obj_t *uic_ConfirmUserButton;
lv_obj_t *uic_SelectUserLabel;
lv_obj_t *ui_Screen1 = NULL;
lv_obj_t *ui_Dropdown1 = NULL;
lv_obj_t *ui_Image1 = NULL;
lv_obj_t *ui_SelectUserLabel = NULL;
lv_obj_t *ui_ConfirmUserButton = NULL;
lv_obj_t *ui_Label2 = NULL;
// event funtions

void ui_event_UserDropdown(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        UserDropdownEvent(e);
        (e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xEE7B01), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen1, lv_color_hex(0x2E1A05), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown1 = lv_dropdown_create(ui_Screen1);
    lv_dropdown_set_options(ui_Dropdown1, users->getUsersDelimit("\n").c_str());
    lv_obj_set_width(ui_Dropdown1, 314);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Dropdown1, -167);
    lv_obj_set_y(ui_Dropdown1, 134);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_set_style_bg_color(ui_Dropdown1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image1, &ui_img_buildshift_brand_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image1, 11);
    lv_obj_set_y(ui_Image1, -157);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SelectUserLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SelectUserLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SelectUserLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SelectUserLabel, -9);
    lv_obj_set_y(ui_SelectUserLabel, -45);
    lv_obj_set_align(ui_SelectUserLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SelectUserLabel, "Select User Menu");
    lv_obj_set_style_text_color(ui_SelectUserLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SelectUserLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SelectUserLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_SelectUserLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SelectUserLabel, lv_color_hex(0x956207), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SelectUserLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SelectUserLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SelectUserLabel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfirmUserButton = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_ConfirmUserButton, 266);
    lv_obj_set_height(ui_ConfirmUserButton, 50);
    lv_obj_set_x(ui_ConfirmUserButton, 197);
    lv_obj_set_y(ui_ConfirmUserButton, 134);
    lv_obj_set_align(ui_ConfirmUserButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfirmUserButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_ConfirmUserButton, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    lv_obj_set_style_bg_color(ui_ConfirmUserButton, lv_color_hex(0xF0A31E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfirmUserButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ConfirmUserButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfirmUserButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *ui_ConfirmUserButtonLabel = lv_label_create(ui_ConfirmUserButton);
    lv_label_set_text(ui_ConfirmUserButtonLabel, "Confirm");
    lv_obj_center(ui_ConfirmUserButtonLabel);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label2, -12);
    lv_obj_set_y(ui_Label2, 26);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Make a selection");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Dropdown1, ui_event_UserDropdown, LV_EVENT_VALUE_CHANGED, NULL);

    uic_SelectUserLabel = ui_SelectUserLabel;
    uic_ConfirmUserButton = ui_ConfirmUserButton;
}

void ui_Screen1_screen_destroy(void)
{
    if (ui_Screen1)
        lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Dropdown1 = NULL;
    ui_Image1 = NULL;
    uic_SelectUserLabel = NULL;
    ui_SelectUserLabel = NULL;
    uic_ConfirmUserButton = NULL;
    ui_ConfirmUserButton = NULL;
    ui_Label2 = NULL;
}
