// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: Brew Tender v.0.1

#ifndef UI_SCREENHOME_H
#define UI_SCREENHOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenHome
extern void ui_screenHome_screen_init(void);
extern void ui_screenHome_screen_destroy(void);
extern lv_obj_t * ui_screenHome;
extern lv_obj_t * ui_labelPressurize;
extern lv_obj_t * ui_sliderPressurize;
extern lv_obj_t * ui_sliderFill;
extern lv_obj_t * ui_switchCheckPoint;
extern lv_obj_t * ui_labelCheckPoint;
extern lv_obj_t * ui_imageLogo;
extern void ui_event_dropdownUser(lv_event_t * e);
extern lv_obj_t * ui_dropdownUser;
extern void ui_event_switchPressurize(lv_event_t * e);
extern lv_obj_t * ui_switchPressurize;
extern void ui_event_switchFill(lv_event_t * e);
extern lv_obj_t * ui_switchFill;
extern lv_obj_t * ui_labelFill;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_screenHome;
extern lv_obj_t * uic_labelPressurize;
extern lv_obj_t * uic_sliderPressurize;
extern lv_obj_t * uic_sliderFill;
extern lv_obj_t * uic_switchCheckPoint;
extern lv_obj_t * uic_labelCheckPoint;
extern lv_obj_t * uic_imageLogo;
extern lv_obj_t * uic_dropdownUser;
extern lv_obj_t * uic_switchPressurize;
extern lv_obj_t * uic_switchFill;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

