// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: Public Address

#include "ui.h"

lv_obj_t * uic_ScreenSettings;
lv_obj_t * ui_ScreenSettings = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions
void ui_event_Label3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_screenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenHome_screen_init);
    }
}

// build funtions

void ui_ScreenSettings_screen_init(void)
{
    ui_ScreenSettings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_button_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, -13);
    lv_obj_set_y(ui_Button2, -31);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -1);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Close");

    lv_obj_add_event_cb(ui_Label3, ui_event_Label3, LV_EVENT_ALL, NULL);
    uic_ScreenSettings = ui_ScreenSettings;

}

void ui_ScreenSettings_screen_destroy(void)
{
    if(ui_ScreenSettings) lv_obj_del(ui_ScreenSettings);

    // NULL screen variables
    uic_ScreenSettings = NULL;
    ui_ScreenSettings = NULL;
    ui_Button2 = NULL;
    ui_Label3 = NULL;

}
