// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: Brew Tender v.0.1

#include "ui.h"

lv_obj_t * uic_switchFill;
lv_obj_t * uic_switchPressurize;
lv_obj_t * uic_dropdownUser;
lv_obj_t * uic_imageLogo;
lv_obj_t * uic_labelCheckPoint;
lv_obj_t * uic_switchCheckPoint;
lv_obj_t * uic_sliderFill;
lv_obj_t * uic_sliderPressurize;
lv_obj_t * uic_labelPressurize;
lv_obj_t * uic_screenHome;
lv_obj_t * ui_screenHome = NULL;
lv_obj_t * ui_labelPressurize = NULL;
lv_obj_t * ui_sliderPressurize = NULL;
lv_obj_t * ui_sliderFill = NULL;
lv_obj_t * ui_switchCheckPoint = NULL;
lv_obj_t * ui_labelCheckPoint = NULL;
lv_obj_t * ui_imageLogo = NULL;
lv_obj_t * ui_dropdownUser = NULL;
lv_obj_t * ui_switchPressurize = NULL;
lv_obj_t * ui_switchFill = NULL;
lv_obj_t * ui_labelFill = NULL;
lv_obj_t * ui_Image1 = NULL;
// event funtions
void ui_event_dropdownUser(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        dropdownUserChanged(e);
    }
}

void ui_event_switchPressurize(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        switchPressurizeChanged(e);
    }
}

void ui_event_switchFill(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        switchFillChanged(e);
    }
}

// build funtions

void ui_screenHome_screen_init(void)
{
    ui_screenHome = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screenHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelPressurize = lv_label_create(ui_screenHome);
    lv_obj_set_width(ui_labelPressurize, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPressurize, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPressurize, -273);
    lv_obj_set_y(ui_labelPressurize, -106);
    lv_obj_set_align(ui_labelPressurize, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPressurize, "Pressurize");

    ui_sliderPressurize = lv_slider_create(ui_screenHome);
    lv_slider_set_value(ui_sliderPressurize, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_sliderPressurize) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_sliderPressurize, 100,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_sliderPressurize, 150);
    lv_obj_set_height(ui_sliderPressurize, 10);
    lv_obj_set_x(ui_sliderPressurize, -254);
    lv_obj_set_y(ui_sliderPressurize, -4);
    lv_obj_set_align(ui_sliderPressurize, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_sliderPressurize, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Pink);
    ui_object_set_themeable_style_property(ui_sliderPressurize, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Pink);
    ui_object_set_themeable_style_property(ui_sliderPressurize, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_Red);
    lv_obj_set_style_bg_grad_dir(ui_sliderPressurize, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_sliderPressurize, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Red);
    ui_object_set_themeable_style_property(ui_sliderPressurize, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Red);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_sliderPressurize, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_sliderPressurize,
                                                                                                       lv_obj_get_style_pad_right(ui_sliderPressurize, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_sliderFill = lv_slider_create(ui_screenHome);
    lv_slider_set_value(ui_sliderFill, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_sliderFill) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_sliderFill, 100, LV_ANIM_OFF);
    lv_obj_set_width(ui_sliderFill, 150);
    lv_obj_set_height(ui_sliderFill, 10);
    lv_obj_set_x(ui_sliderFill, -254);
    lv_obj_set_y(ui_sliderFill, 178);
    lv_obj_set_align(ui_sliderFill, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_sliderFill, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_sliderFill, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);
    ui_object_set_themeable_style_property(ui_sliderFill, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_Blue);
    lv_obj_set_style_bg_grad_dir(ui_sliderFill, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_sliderFill, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_sliderFill, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_sliderFill, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_sliderFill,
                                                                                                 lv_obj_get_style_pad_right(ui_sliderFill, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_switchCheckPoint = lv_switch_create(ui_screenHome);
    lv_obj_set_width(ui_switchCheckPoint, 50);
    lv_obj_set_height(ui_switchCheckPoint, 25);
    lv_obj_set_x(ui_switchCheckPoint, 280);
    lv_obj_set_y(ui_switchCheckPoint, -164);
    lv_obj_set_align(ui_switchCheckPoint, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_switchCheckPoint, LV_STATE_DISABLED);       /// States
    ui_object_set_themeable_style_property(ui_switchCheckPoint, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Red);
    ui_object_set_themeable_style_property(ui_switchCheckPoint, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Red);
    lv_obj_set_style_transform_scale(ui_switchCheckPoint, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelCheckPoint = lv_label_create(ui_screenHome);
    lv_obj_set_width(ui_labelCheckPoint, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelCheckPoint, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelCheckPoint, 292);
    lv_obj_set_y(ui_labelCheckPoint, -192);
    lv_obj_set_align(ui_labelCheckPoint, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelCheckPoint, "Check Point");

    ui_imageLogo = lv_image_create(ui_screenHome);
    lv_image_set_src(ui_imageLogo, &ui_img_1324469499);
    lv_obj_set_width(ui_imageLogo, LV_SIZE_CONTENT);   /// 51
    lv_obj_set_height(ui_imageLogo, LV_SIZE_CONTENT);    /// 53
    lv_obj_set_x(ui_imageLogo, 354);
    lv_obj_set_y(ui_imageLogo, 203);
    lv_obj_set_align(ui_imageLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imageLogo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imageLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_imageLogo, 320);

    ui_dropdownUser = lv_dropdown_create(ui_screenHome);
    lv_dropdown_set_options(ui_dropdownUser, "User...\nJennie\nAlex");
    lv_obj_set_width(ui_dropdownUser, 150);
    lv_obj_set_height(ui_dropdownUser, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dropdownUser, -272);
    lv_obj_set_y(ui_dropdownUser, -184);
    lv_obj_set_align(ui_dropdownUser, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dropdownUser, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_switchPressurize = lv_switch_create(ui_screenHome);
    lv_obj_set_width(ui_switchPressurize, 50);
    lv_obj_set_height(ui_switchPressurize, 25);
    lv_obj_set_x(ui_switchPressurize, -301);
    lv_obj_set_y(ui_switchPressurize, -72);
    lv_obj_set_align(ui_switchPressurize, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_switchPressurize, 5);
    ui_object_set_themeable_style_property(ui_switchPressurize, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Pink);
    ui_object_set_themeable_style_property(ui_switchPressurize, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Pink);
    ui_object_set_themeable_style_property(ui_switchPressurize, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_Red);
    lv_obj_set_style_bg_grad_dir(ui_switchPressurize, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_scale(ui_switchPressurize, 512, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_switchPressurize, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Pink);
    ui_object_set_themeable_style_property(ui_switchPressurize, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Pink);
    ui_object_set_themeable_style_property(ui_switchPressurize, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_GRAD_COLOR, _ui_theme_color_Red);
    lv_obj_set_style_bg_grad_dir(ui_switchPressurize, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_switchFill = lv_switch_create(ui_screenHome);
    lv_obj_set_width(ui_switchFill, 50);
    lv_obj_set_height(ui_switchFill, 25);
    lv_obj_set_x(ui_switchFill, -302);
    lv_obj_set_y(ui_switchFill, 93);
    lv_obj_set_align(ui_switchFill, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_switchFill, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_switchFill, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);
    ui_object_set_themeable_style_property(ui_switchFill, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_Blue);
    lv_obj_set_style_bg_grad_dir(ui_switchFill, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_scale(ui_switchFill, 512, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelFill = lv_label_create(ui_screenHome);
    lv_obj_set_width(ui_labelFill, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelFill, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelFill, -279);
    lv_obj_set_y(ui_labelFill, 61);
    lv_obj_set_align(ui_labelFill, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelFill, "Fill");

    ui_Image1 = lv_image_create(ui_screenHome);
    lv_image_set_src(ui_Image1, &ui_img_possum_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 393
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 412
    lv_obj_set_x(ui_Image1, 20);
    lv_obj_set_y(ui_Image1, 10);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_dropdownUser, ui_event_dropdownUser, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switchPressurize, ui_event_switchPressurize, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switchFill, ui_event_switchFill, LV_EVENT_ALL, NULL);
    uic_screenHome = ui_screenHome;
    uic_labelPressurize = ui_labelPressurize;
    uic_sliderPressurize = ui_sliderPressurize;
    uic_sliderFill = ui_sliderFill;
    uic_switchCheckPoint = ui_switchCheckPoint;
    uic_labelCheckPoint = ui_labelCheckPoint;
    uic_imageLogo = ui_imageLogo;
    uic_dropdownUser = ui_dropdownUser;
    uic_switchPressurize = ui_switchPressurize;
    uic_switchFill = ui_switchFill;

}

void ui_screenHome_screen_destroy(void)
{
    if(ui_screenHome) lv_obj_del(ui_screenHome);

    // NULL screen variables
    uic_screenHome = NULL;
    ui_screenHome = NULL;
    uic_labelPressurize = NULL;
    ui_labelPressurize = NULL;
    uic_sliderPressurize = NULL;
    ui_sliderPressurize = NULL;
    uic_sliderFill = NULL;
    ui_sliderFill = NULL;
    uic_switchCheckPoint = NULL;
    ui_switchCheckPoint = NULL;
    uic_labelCheckPoint = NULL;
    ui_labelCheckPoint = NULL;
    uic_imageLogo = NULL;
    ui_imageLogo = NULL;
    uic_dropdownUser = NULL;
    ui_dropdownUser = NULL;
    uic_switchPressurize = NULL;
    ui_switchPressurize = NULL;
    uic_switchFill = NULL;
    ui_switchFill = NULL;
    ui_labelFill = NULL;
    ui_Image1 = NULL;

}
