// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: Public Address

#ifndef UI_SCREENHOME_H
#define UI_SCREENHOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenHome
extern void ui_screenHome_screen_init(void);
extern void ui_screenHome_screen_destroy(void);
extern lv_obj_t * ui_screenHome;
extern lv_obj_t * ui_imageLogo;
extern void ui_event_dropdownUser(lv_event_t * e);
extern lv_obj_t * ui_dropdownUser;
extern void ui_event_buttonPlay(lv_event_t * e);
extern lv_obj_t * ui_buttonPlay;
extern lv_obj_t * ui_Label1;
extern void ui_event_switchBlink(lv_event_t * e);
extern lv_obj_t * ui_switchBlink;
extern lv_obj_t * ui_labelBlink;
extern void ui_event_buttonStop(lv_event_t * e);
extern lv_obj_t * ui_buttonStop;
extern lv_obj_t * ui_labelStop;
extern lv_obj_t * ui_buttonSettings;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_screenHome;
extern lv_obj_t * uic_imageLogo;
extern lv_obj_t * uic_dropdownUser;
extern lv_obj_t * uic_buttonPlay;
extern lv_obj_t * uic_switchBlink;
extern lv_obj_t * uic_labelBlink;
extern lv_obj_t * uic_labelStop;
extern lv_obj_t * uic_buttonSettings;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

