// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: Public Address

#include "ui.h"

lv_obj_t * uic_buttonSettings;
lv_obj_t * uic_labelStop;
lv_obj_t * uic_labelBlink;
lv_obj_t * uic_switchBlink;
lv_obj_t * uic_buttonPlay;
lv_obj_t * uic_dropdownUser;
lv_obj_t * uic_imageLogo;
lv_obj_t * uic_screenHome;
lv_obj_t * ui_screenHome = NULL;
lv_obj_t * ui_imageLogo = NULL;
lv_obj_t * ui_dropdownUser = NULL;
lv_obj_t * ui_buttonPlay = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_switchBlink = NULL;
lv_obj_t * ui_labelBlink = NULL;
lv_obj_t * ui_buttonStop = NULL;
lv_obj_t * ui_labelStop = NULL;
lv_obj_t * ui_buttonSettings = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions
void ui_event_dropdownUser(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        dropdownUserChanged(e);
    }
}

void ui_event_buttonPlay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        PlayButtonPressed(e);
    }
}

void ui_event_switchBlink(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        BlinkEnabled(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        BlinkDisabled(e);
    }
}

void ui_event_buttonStop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        StopButtonPressed(e);
    }
}

// build funtions

void ui_screenHome_screen_init(void)
{
    ui_screenHome = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screenHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screenHome, lv_color_hex(0xF68E40), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_screenHome, &ui_img_94336299, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_screenHome, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imageLogo = lv_image_create(ui_screenHome);
    lv_image_set_src(ui_imageLogo, &ui_img_1324469499);
    lv_obj_set_width(ui_imageLogo, LV_SIZE_CONTENT);   /// 51
    lv_obj_set_height(ui_imageLogo, LV_SIZE_CONTENT);    /// 53
    lv_obj_set_x(ui_imageLogo, 355);
    lv_obj_set_y(ui_imageLogo, 205);
    lv_obj_set_align(ui_imageLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imageLogo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imageLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_imageLogo, 320);

    ui_dropdownUser = lv_dropdown_create(ui_screenHome);
    lv_dropdown_set_options(ui_dropdownUser, "User...\nJennie\nAlex");
    lv_obj_set_width(ui_dropdownUser, 150);
    lv_obj_set_height(ui_dropdownUser, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dropdownUser, -287);
    lv_obj_set_y(ui_dropdownUser, -193);
    lv_obj_set_align(ui_dropdownUser, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dropdownUser, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_buttonPlay = lv_button_create(ui_screenHome);
    lv_obj_set_width(ui_buttonPlay, 100);
    lv_obj_set_height(ui_buttonPlay, 50);
    lv_obj_set_x(ui_buttonPlay, -309);
    lv_obj_set_y(ui_buttonPlay, -108);
    lv_obj_set_align(ui_buttonPlay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonPlay, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonPlay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonPlay, lv_color_hex(0x40F6B7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonPlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_buttonPlay);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "PLAY");
    ui_object_set_themeable_style_property(ui_Label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_Label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Orange);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switchBlink = lv_switch_create(ui_screenHome);
    lv_obj_set_width(ui_switchBlink, 50);
    lv_obj_set_height(ui_switchBlink, 25);
    lv_obj_set_x(ui_switchBlink, -310);
    lv_obj_set_y(ui_switchBlink, 85);
    lv_obj_set_align(ui_switchBlink, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_switchBlink, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_switchBlink, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Orange);

    lv_obj_set_style_bg_color(ui_switchBlink, lv_color_hex(0xF1B79F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switchBlink, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_labelBlink = lv_label_create(ui_screenHome);
    lv_obj_set_width(ui_labelBlink, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBlink, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBlink, -311);
    lv_obj_set_y(ui_labelBlink, 51);
    lv_obj_set_align(ui_labelBlink, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBlink, "Blink");

    ui_buttonStop = lv_button_create(ui_screenHome);
    lv_obj_set_width(ui_buttonStop, 100);
    lv_obj_set_height(ui_buttonStop, 50);
    lv_obj_set_x(ui_buttonStop, -307);
    lv_obj_set_y(ui_buttonStop, -23);
    lv_obj_set_align(ui_buttonStop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonStop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonStop, lv_color_hex(0x41F6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelStop = lv_label_create(ui_buttonStop);
    lv_obj_set_width(ui_labelStop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelStop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelStop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelStop, "STOP");
    lv_obj_set_style_text_color(ui_labelStop, lv_color_hex(0xF6A539), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelStop, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonSettings = lv_button_create(ui_screenHome);
    lv_obj_set_width(ui_buttonSettings, 100);
    lv_obj_set_height(ui_buttonSettings, 50);
    lv_obj_set_x(ui_buttonSettings, 318);
    lv_obj_set_y(ui_buttonSettings, -197);
    lv_obj_set_align(ui_buttonSettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonSettings, lv_color_hex(0xFAC949), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_buttonSettings);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Settings");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_dropdownUser, ui_event_dropdownUser, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonPlay, ui_event_buttonPlay, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switchBlink, ui_event_switchBlink, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonStop, ui_event_buttonStop, LV_EVENT_ALL, NULL);
    uic_screenHome = ui_screenHome;
    uic_imageLogo = ui_imageLogo;
    uic_dropdownUser = ui_dropdownUser;
    uic_buttonPlay = ui_buttonPlay;
    uic_switchBlink = ui_switchBlink;
    uic_labelBlink = ui_labelBlink;
    uic_labelStop = ui_labelStop;
    uic_buttonSettings = ui_buttonSettings;

}

void ui_screenHome_screen_destroy(void)
{
    if(ui_screenHome) lv_obj_del(ui_screenHome);

    // NULL screen variables
    uic_screenHome = NULL;
    ui_screenHome = NULL;
    uic_imageLogo = NULL;
    ui_imageLogo = NULL;
    uic_dropdownUser = NULL;
    ui_dropdownUser = NULL;
    uic_buttonPlay = NULL;
    ui_buttonPlay = NULL;
    ui_Label1 = NULL;
    uic_switchBlink = NULL;
    ui_switchBlink = NULL;
    uic_labelBlink = NULL;
    ui_labelBlink = NULL;
    ui_buttonStop = NULL;
    uic_labelStop = NULL;
    ui_labelStop = NULL;
    uic_buttonSettings = NULL;
    ui_buttonSettings = NULL;
    ui_Label2 = NULL;

}
