// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: Public Address

#ifndef UI_SCREENSETTINGS_H
#define UI_SCREENSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenSettings
extern void ui_ScreenSettings_screen_init(void);
extern void ui_ScreenSettings_screen_destroy(void);
extern lv_obj_t * ui_ScreenSettings;
extern lv_obj_t * ui_Button2;
extern void ui_event_Label3(lv_event_t * e);
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenSettings;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

