// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: bs_kettle_fill

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Dropdown1;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_SelectUserLabel;
extern lv_obj_t *ui_ConfirmUserButton;
extern lv_obj_t *ui_Label2;
// CUSTOM VARIABLES
extern lv_obj_t *uic_SelectUserLabel;
extern lv_obj_t *uic_ConfirmUserButton;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

