// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: Brew Tender v.0.1

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_RED 0
#define UI_THEME_COLOR_BLUE 1
#define UI_THEME_COLOR_YELLOW 2
#define UI_THEME_COLOR_LIGHTBLUE 3
#define UI_THEME_COLOR_PINK 4

#define UI_THEME_DEFAULT 0

#define UI_THEME_KETTLEFILL 1

extern const ui_theme_variable_t _ui_theme_color_Red[2];
extern const ui_theme_variable_t _ui_theme_alpha_Red[2];

extern const ui_theme_variable_t _ui_theme_color_Blue[2];
extern const ui_theme_variable_t _ui_theme_alpha_Blue[2];

extern const ui_theme_variable_t _ui_theme_color_Yellow[2];
extern const ui_theme_variable_t _ui_theme_alpha_Yellow[2];

extern const ui_theme_variable_t _ui_theme_color_LightBlue[2];
extern const ui_theme_variable_t _ui_theme_alpha_LightBlue[2];

extern const ui_theme_variable_t _ui_theme_color_Pink[2];
extern const ui_theme_variable_t _ui_theme_alpha_Pink[2];

extern const uint32_t * ui_theme_colors[2];
extern const uint8_t * ui_theme_alphas[2];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
