// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: Brew Tender v.0.1

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Red[2] = {0x9C2841, 0x9C2841};
const ui_theme_variable_t _ui_theme_alpha_Red[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Blue[2] = {0x6693F3, 0x6693F3};
const ui_theme_variable_t _ui_theme_alpha_Blue[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Yellow[2] = {0xFAC949, 0xFAC949};
const ui_theme_variable_t _ui_theme_alpha_Yellow[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_LightBlue[2] = {0x00E9FF, 0x00E9FF};
const ui_theme_variable_t _ui_theme_alpha_LightBlue[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Pink[2] = {0xFF7173, 0xFF7173};
const ui_theme_variable_t _ui_theme_alpha_Pink[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

