// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: bs_kettle_fill

#include "ui/ui.h"
#include "Globals.h"
#include "ui/events/events.h"

lv_obj_t *uic_ConfirmLabel1;
lv_obj_t *uic_UserDisplayLabel;
lv_obj_t *uic_ConfirmUserButton;
lv_obj_t *uic_SelectUserLabel;
lv_obj_t *uic_BSLogo;
lv_obj_t *ui_UserSelectionScreen = nullptr;
lv_obj_t *ui_Dropdown1 = nullptr;
lv_obj_t *ui_BSLogo = nullptr;
lv_obj_t *ui_SelectUserLabel = nullptr;
lv_obj_t *ui_ConfirmUserButton = nullptr;
lv_obj_t *ui_UserDisplayLabel = nullptr;
lv_obj_t *ui_ConfirmLabel1 = nullptr;

// event funtions
void ui_event_user_dropdown(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        handleUserDropdownEvent(e);
        (e);
    }
}

void ui_event_ConfirmUserButton(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // if (event_code == LV_EVENT_CLICKED)
    // {
    //     _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    // }
}

// build funtions

void ui_UserSelection_screen_init(void)
{
    try
    {
        logger.info("[UI] Initializing User Selection screen");

        ui_UserSelectionScreen = lv_obj_create(nullptr);
        if (!ui_UserSelectionScreen)
        {
            logger.error("[UI] Failed to create UserSelectionScreen");
            return;
        }

        lv_obj_remove_flag(ui_UserSelectionScreen, LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_set_style_bg_color(ui_UserSelectionScreen, lv_color_hex(0xEE7B01),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);

        // --- Dropdown ---
        if (!users)
        {
            logger.error("[UI] 'users' pointer is nullptr, cannot populate dropdown!");
        }

        ui_Dropdown1 = lv_dropdown_create(ui_UserSelectionScreen);
        if (ui_Dropdown1)
        {
            const String userListStd =
                users
                    ? users->getUsersDelimit("\n")
                    : "NONE";

            lv_dropdown_set_options(ui_Dropdown1, userListStd.c_str());

            lv_obj_set_width(ui_Dropdown1, 314);
            lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);
            lv_obj_set_x(ui_Dropdown1, -167);
            lv_obj_set_y(ui_Dropdown1, 134);
            lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
            lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
            lv_obj_set_style_bg_color(ui_Dropdown1, lv_color_hex(0xFFFFFF),
                                      LV_PART_MAIN | LV_STATE_DEFAULT);
        }
        else
        {
            logger.error("[UI] Failed to create Dropdown1");
        }

        // --- Logo ---
        ui_BSLogo = lv_image_create(ui_UserSelectionScreen);
        if (ui_BSLogo)
            lv_image_set_src(ui_BSLogo, &ui_img_buildshift_brand_png);

        // --- Labels ---
        ui_SelectUserLabel = lv_label_create(ui_UserSelectionScreen);
        if (ui_SelectUserLabel)
            lv_label_set_text(ui_SelectUserLabel, "Select User Menu");

        ui_UserDisplayLabel = lv_label_create(ui_UserSelectionScreen);
        if (ui_UserDisplayLabel)
            lv_label_set_text(ui_UserDisplayLabel, "Make a selection");

        ui_ConfirmLabel1 = lv_label_create(ui_UserSelectionScreen);
        if (ui_ConfirmLabel1)
            lv_label_set_text(ui_ConfirmLabel1, "Confirm");

        // --- Button ---
        ui_ConfirmUserButton = lv_button_create(ui_UserSelectionScreen);

        // --- Event callbacks ---
        if (ui_Dropdown1)
            lv_obj_add_event_cb(ui_Dropdown1, ui_event_user_dropdown, LV_EVENT_ALL, nullptr);
        if (ui_ConfirmUserButton)
            lv_obj_add_event_cb(ui_ConfirmUserButton, ui_event_ConfirmUserButton, LV_EVENT_ALL, nullptr);

        // --- Global access pointers ---
        uic_BSLogo = ui_BSLogo;
        uic_SelectUserLabel = ui_SelectUserLabel;
        uic_ConfirmUserButton = ui_ConfirmUserButton;
        uic_UserDisplayLabel = ui_UserDisplayLabel;
        uic_ConfirmLabel1 = ui_ConfirmLabel1;

        // --- Load the screen ---
        lv_scr_load(ui_UserSelectionScreen);

        logger.info("[UI] User Selection screen initialized successfully");
    }
    catch (const std::exception &ex)
    {
        logger.error(String("[UI] Exception in UserSelection init: ") + ex.what());
    }
    catch (...)
    {
        logger.error("[UI] Unknown exception in UserSelection init");
    }
}

void ui_UserSelection_screen_destroy(void)
{
    if (ui_UserSelectionScreen)
        lv_obj_del(ui_UserSelectionScreen);

    // nullptr screen variables
    ui_UserSelectionScreen = nullptr;
    ui_Dropdown1 = nullptr;
    uic_BSLogo = nullptr;
    ui_BSLogo = nullptr;
    uic_SelectUserLabel = nullptr;
    ui_SelectUserLabel = nullptr;
    uic_ConfirmUserButton = nullptr;
    ui_ConfirmUserButton = nullptr;
    uic_UserDisplayLabel = nullptr;
    ui_UserDisplayLabel = nullptr;
    uic_ConfirmLabel1 = nullptr;
    ui_ConfirmLabel1 = nullptr;
}
