// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: bs_kettle_fill

#include "ui/ui.h"
#include "Globals.h"
#include "ui/events/events.h"

lv_obj_t *uic_ConfirmLabel1;
lv_obj_t *uic_UserDisplayLabel;
lv_obj_t *uic_ConfirmUserButton;
lv_obj_t *uic_SelectUserLabel;
lv_obj_t *uic_BSLogo;
lv_obj_t *ui_UserSelectionScreen = NULL;
lv_obj_t *ui_Dropdown1 = NULL;
lv_obj_t *ui_BSLogo = NULL;
lv_obj_t *ui_SelectUserLabel = NULL;
lv_obj_t *ui_ConfirmUserButton = NULL;
lv_obj_t *ui_UserDisplayLabel = NULL;
lv_obj_t *ui_ConfirmLabel1 = NULL;

// event funtions
void ui_event_user_dropdown(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        handleUserDropdownEvent(e);
        (e);
    }
}

void ui_event_ConfirmUserButton(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_UserSelection_screen_init(void)
{
    ui_UserSelectionScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_UserSelectionScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_UserSelectionScreen, lv_color_hex(0xEE7B01), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UserSelectionScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_UserSelectionScreen, lv_color_hex(0x2E1A05), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_UserSelectionScreen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown1 = lv_dropdown_create(ui_UserSelectionScreen);
    // lv_dropdown_set_options(ui_Dropdown1, "Option 1\nOption 2\nOption 3");
    lv_dropdown_set_options(ui_Dropdown1, users->getUsersDelimit("\n").c_str());
    lv_obj_set_width(ui_Dropdown1, 314);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Dropdown1, -167);
    lv_obj_set_y(ui_Dropdown1, 134);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_set_style_bg_color(ui_Dropdown1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BSLogo = lv_image_create(ui_UserSelectionScreen);
    lv_image_set_src(ui_BSLogo, &ui_img_buildshift_brand_png);
    lv_obj_set_width(ui_BSLogo, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_BSLogo, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_BSLogo, 11);
    lv_obj_set_y(ui_BSLogo, -157);
    lv_obj_set_align(ui_BSLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BSLogo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BSLogo, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SelectUserLabel = lv_label_create(ui_UserSelectionScreen);
    lv_obj_set_width(ui_SelectUserLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SelectUserLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SelectUserLabel, -9);
    lv_obj_set_y(ui_SelectUserLabel, -45);
    lv_obj_set_align(ui_SelectUserLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SelectUserLabel, "Select User Menu");
    lv_obj_set_style_text_color(ui_SelectUserLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SelectUserLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SelectUserLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_SelectUserLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SelectUserLabel, lv_color_hex(0x956207), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SelectUserLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SelectUserLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SelectUserLabel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfirmUserButton = lv_button_create(ui_UserSelectionScreen);
    lv_obj_set_width(ui_ConfirmUserButton, 266);
    lv_obj_set_height(ui_ConfirmUserButton, 50);
    lv_obj_set_x(ui_ConfirmUserButton, 197);
    lv_obj_set_y(ui_ConfirmUserButton, 134);
    lv_obj_set_align(ui_ConfirmUserButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfirmUserButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_ConfirmUserButton, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    lv_obj_set_style_bg_color(ui_ConfirmUserButton, lv_color_hex(0xF0A31E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfirmUserButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ConfirmUserButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfirmUserButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UserDisplayLabel = lv_label_create(ui_UserSelectionScreen);
    lv_obj_set_width(ui_UserDisplayLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_UserDisplayLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_UserDisplayLabel, -12);
    lv_obj_set_y(ui_UserDisplayLabel, 26);
    lv_obj_set_align(ui_UserDisplayLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UserDisplayLabel, "Make a selection");
    lv_obj_set_style_text_color(ui_UserDisplayLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UserDisplayLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UserDisplayLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfirmLabel1 = lv_label_create(ui_UserSelectionScreen);
    lv_obj_set_width(ui_ConfirmLabel1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_ConfirmLabel1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_ConfirmLabel1, 196);
    lv_obj_set_y(ui_ConfirmLabel1, 135);
    lv_obj_set_align(ui_ConfirmLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfirmLabel1, "Confirm");
    lv_obj_set_style_text_font(ui_ConfirmLabel1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Dropdown1, ui_event_user_dropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConfirmUserButton, ui_event_ConfirmUserButton, LV_EVENT_ALL, NULL);
    uic_BSLogo = ui_BSLogo;
    uic_SelectUserLabel = ui_SelectUserLabel;
    uic_ConfirmUserButton = ui_ConfirmUserButton;
    uic_UserDisplayLabel = ui_UserDisplayLabel;
    uic_ConfirmLabel1 = ui_ConfirmLabel1;
}

void ui_UserSelection_screen_destroy(void)
{
    if (ui_UserSelectionScreen)
        lv_obj_del(ui_UserSelectionScreen);

    // NULL screen variables
    ui_UserSelectionScreen = NULL;
    ui_Dropdown1 = NULL;
    uic_BSLogo = NULL;
    ui_BSLogo = NULL;
    uic_SelectUserLabel = NULL;
    ui_SelectUserLabel = NULL;
    uic_ConfirmUserButton = NULL;
    ui_ConfirmUserButton = NULL;
    uic_UserDisplayLabel = NULL;
    ui_UserDisplayLabel = NULL;
    uic_ConfirmLabel1 = NULL;
    ui_ConfirmLabel1 = NULL;
}
